<?php

namespace AppBundle\Entity;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{

    /** Gets orders for a specific page, keeping in mind pages' limit of orders being displayed
     * @param $per_page
     * @param $page_number
     * @return array selected orders
     */
    public function getOrdersForPage($per_page, $page_number)
    {
        $query = $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.joiningDeadline > :joining_deadline')
            ->setParameter('joining_deadline', date("Y-m-d H:i:s"))
            ->getQuery();

        return $query
            ->setFirstResult( ($page_number - 1) * $per_page )
            ->setMaxResults( $per_page )
            ->getResult();
    }
}
